### PR TITLE
Current progress for redesign FileSend using TypeScript

### PR DESCRIPTION
**Pull request by arpit-saxena**
- All the TS code goes into lib/ with the server side and client side code going into lib/server/ and lib/client/ respectively.
- Compiled JS goes to src/* and the browserified bundle goes to js/*
- There are some remnants of the old code still left, kept around for referring to, if needed.

### CODE REVIEW

**Comment by arpit-saxena** [comment]
Also, this doesn't have any frontend right now. So, don't deploy it.

**Comment by ankurshaswat** [comment]
Restructure the project in the following way :-
All source code files must be in src/*
All compiled files must be generated in build folder. (For example try building the starter react app)
All other files used by the website (static) must be inside the public folder (in folders css,js,media)

**Comment by ankurshaswat** [comment]
After the above job :-
Install and run npm-check to see unused packages to remove and outdated packages to update.

**Comment by ankurshaswat** [comment]
Also instead of just putting in rules to stop warnings try to follow the suggestions instead.
Clear eslintrc rule exceptions.

**Comment by ankurshaswat** [comment]
When using es6 no need to use 'require' statements.
Remove all of these.

Use export default <funcName> instead of export =

**Comment by ankurshaswat** [comment]
Merged into develop branch

Put PR in that branch from now.

**Pull request closed without merging**
